-- Create status enum (add more if needed)
create type work_status as enum ('in_office', 'wfh', 'off', 'sick', 'vacation');

-- Public profiles table (syncs with Supabase Auth)
create table profiles (
  id uuid references auth.users not null primary key,
  email text unique not null,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Daily logs table (core data)
create table daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  date date not null,
  status work_status not null default 'in_office',
  activities text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, date) -- Prevent duplicate logs for the same user on the same day
);

-- Auto-create profile when user signs up
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Enable RLS on both tables
alter table profiles enable row level security;
alter table daily_logs enable row level security;

-- Profiles: Everyone can read, only you can edit your own
create policy "All authenticated users can read profiles"
on profiles for select to authenticated using (true);

create policy "Users can update their own profile"
on profiles for update to authenticated using (auth.uid() = id);

-- Daily logs: Everyone can read, only you can edit your own
create policy "All authenticated users can read daily logs"
on daily_logs for select to authenticated using (true);

create policy "Users can insert their own logs"
on daily_logs for insert to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own logs"
on daily_logs for update to authenticated
using (auth.uid() = user_id);

-- Enable realtime updates (for instant status refreshes)
alter publication supabase_realtime add table daily_logs;


-- Block signups from any email not in your company domain
create function public.check_email_domain()
returns trigger as $$
begin
  -- Replace with your actual company domain(s)
  if new.email not like '%@kawo.com' then
    raise exception 'Only @kawo.com emails are allowed to access this site';
  end if;
  return new;
end;
$$ language plpgsql security definer;

create trigger block_non_company_signups
  before insert on auth.users
  for each row execute function public.check_email_domain();