-- Create status enum (add more if needed)
create type work_status as enum ('in_office', 'wfh', 'off', 'sick', 'vacation');

-- Public profiles table (syncs with Supabase Auth)
create table profiles (
  id uuid references auth.users not null primary key,
  email text unique not null,
  name text,
  avatar_url text,
  is_admin boolean not null default false,
  is_hidden boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Daily logs table (core data)
create table daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  date date not null,
  status work_status not null default 'in_office',
  activities text,
  activities_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, date) -- Prevent duplicate logs for the same user on the same day
);

-- Auto-create profile when user signs up
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, avatar_url)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Data API grants (required for new tables after Supabase's May 30, 2026 rollout)
grant select, update, delete on public.profiles to authenticated;
grant select on public.profiles to anon;
grant select, insert, update, delete on public.daily_logs to authenticated;

-- Enable RLS on both tables
alter table profiles enable row level security;
alter table daily_logs enable row level security;

-- Helper: is the caller an admin? SECURITY DEFINER avoids RLS recursion when
-- a policy on `profiles` needs to look up `profiles.is_admin`.
create function public.is_admin(uid uuid)
returns boolean as $$
  select coalesce((select is_admin from public.profiles where id = uid), false);
$$ language sql stable security definer;

-- Profiles: Everyone can read, only you (or admins) can edit
create policy "All authenticated users can read profiles"
on profiles for select to authenticated using (true);

create policy "Users can update their own profile"
on profiles for update to authenticated using (auth.uid() = id);

create policy "Admins can update any profile"
on profiles for update to authenticated using (public.is_admin(auth.uid()));

create policy "Admins can delete any profile"
on profiles for delete to authenticated using (public.is_admin(auth.uid()));

-- Daily logs: Everyone can read, only you can edit your own
create policy "All authenticated users can read daily logs"
on daily_logs for select to authenticated using (true);

create policy "Users can insert their own logs"
on daily_logs for insert to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own logs"
on daily_logs for update to authenticated
using (auth.uid() = user_id);

-- Block signups from any email not in your company domain
create function public.check_email_domain()
returns trigger as $$
begin
  -- Replace with your actual company domain(s)
  if new.email not like '%@kawo.com' then
    raise exception 'Only @kawo.com emails are allowed to access this site';
  end if;
  return new;
end;
$$ language plpgsql security definer;

create trigger block_non_company_signups
  before insert on auth.users
  for each row execute function public.check_email_domain();

-- Create RPC to get the most recent date with more than min_logs
create or replace function public.get_last_active_date(min_logs integer, current_date_str text)
returns date as $$
  select date 
  from public.daily_logs 
  where date < current_date_str::date
  group by date 
  having count(*) > min_logs 
  order by date desc 
  limit 1;
$$ language sql stable security definer;